fix: 明示的にサービスアカウントを指定しないとデフォルトのサービスアカウントを探しにいってしまうため、利用するサービスアカウントを指定する
Run google-github-actions/deploy-cloud-functions@v1
Created zip file from './src/02_push_to_repo' at '/tmp/cfsrc-50434836942f4da0dabc28d4.zip'
Creating new Cloud Function deployment
Error: google-github-actions/deploy-cloud-functions failed with: failed to POST https://cloudfunctions.googleapis.com/v1/projects/***/locations/***/functions: (400) {
  "error": {
    "code": 400,
    "message": "Default service account '***@appspot.gserviceaccount.com' doesn't exist. Please recreate this account or specify a different account. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.",
    "status": "FAILED_PRECONDITION"
  }
}